# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "Installing Software..."
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "fasmat/ubuntu2204-desktop"
  config.vm.synced_folder ".", "/hostshare", type: "virtualbox", automount: true, create: true, owner: "vagrant", group: "vagrant"

  # Kubernetes Jumper Server
  config.vm.define "linux" do |node|
  
    node.vm.box               = "fasmat/ubuntu2204-desktop"
    node.vm.box_check_update  = false
    node.vm.hostname          = "linux"

    #node.vm.network "public_network"
    node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
    #node.vm.network "public_network", bridge: "Realtek PCIe GbE Family Controller"
    node.vm.provider "virtualbox" do |vb|
      vb.name    = "linux"
      vb.memory  = 8096
      vb.cpus    =  4

      # vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      # vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      # https://hameedullah.com/vagrant-101-basic-virtual-machine-customizations.html
      # Disable USB
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
      # https://gist.github.com/mxey/ce6911724acee4517692bf683ee90624
      # Prevent VirtualBox from interfering with host audio stack
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end

    node.vm.provision "shell", privileged: true, inline: $script
  end
  
end